#!/bin/bash -e

# Pin 12 on P9 is gpio1[28]
# since gpio1 is at offset 32 in the linux gpio driver namespace, we
# compute 32 + 28 = 60. So we want gpio60.

# Pin 15 pn P9 is gpio1[16] which translates to 32 + 16 = gpio48

# Pin 12 will be used as the reset signal. I haven't had a use for pin 15.

# Pin 12 (reset signal for target BBB)
if [ ! -d /sys/class/gpio/gpio60 ]; then 
	echo 60 > /sys/class/gpio/export;
fi

# Pin 15
if [ ! -d /sys/class/gpio/gpio48 ]; then 
	echo 48 > /sys/class/gpio/export;
fi

# We generally don't want pin 15 to be high at this time..
echo low > /sys/class/gpio/gpio48/direction

# Initialize Pin 12 to low (we don't have to wait for it to stabilize)
echo low > /sys/class/gpio/gpio60/direction

# Reset the machine. (pin 12 performs this action).
echo 1 > /sys/class/gpio/gpio60/value

# let it take effect.
sleep .2

# Unreset the machine, and let it boot however it is configured.
echo 0 > /sys/class/gpio/gpio60/value

echo Done.
