#! /bin/bash -e

# kermit seems to mess up all the time, so I wrote this instead to send the
# image to the BBB. It seems to work much better. Ensure kermit is not running
# when this is working, otherwise they argue over the serial port
# configuration.

DEV=/dev/ttyUSB0

if [ "x$1" = "x" -o ! -f "$1" ]; then
	echo Please supply a file to transfer.
fi

# Turn off XON/XOFF, turn off RTS/CTS handshake, 8 data bits, no parity, one
# stop bit, don't clear 8th bit, baud is 115200

stty -ixon -crtscts cs8 -parenb -cstopb -istrip -F $DEV 115200

# and then send the file (1024 byte blocks and 16-bit crc enabled)
# through the serial port. using the xmodem-crc protocol.

sx -k -o -vv $1 < $DEV > $DEV
